### ISSUE TITLE
Feature Request: Error pages

### ISSUE THREAD

**Issue by Brekmister** [superhawk610/multicast#10]
I think it would be useful to know whether if something is broken or not. I can think of several ways of doing this.

Someone else can figure how this should work.

**Comment by superhawk610** [comment]
What about status warnings that appear persistently in a colored bar across the top of the page, something like "Unable to connect to Mongo" or "Registered receiver XXX not connected"?

**Comment by superhawk610** [comment]
This would be a nice feature to complement a config script, to catch any errors that crop up or fall through the cracks after initial setup. I'll incorporate this in my PR for #9.
