### ISSUE TITLE
Feature Request: Dockerfile

### ISSUE THREAD

**Issue by ocelotsloth** [superhawk610/multicast#11]
I'm going to be writing this anyway so I'll make a pull request in the next day or so if there's interest for it. Combined with a docker-compose file to pull in mongo, it'll make deployment a breeze.

**Comment by Brekmister** [comment]
Any new updates on a dockerfile?

**Comment by ocelotsloth** [comment]
I ended up spending more time last week working on getting this deployed on metal as well as attaching some channels to some slide decks that don't render at 5 frames per second. When I get into work on Monday I'll tinker with that to add it as a default option.

That said, I have been turning this over in my head and there are a few issues I need to figure out how to get working on the physical networking side first.

I work at a High School, so we smartly have the chrome casts on our internal trusted wireless network so that our students can't cast to the televisions. The issue this causes is that the server has to be on the same broadcast domain as the chrome casts in order to find them. To deploy on metal, this is as simple as configuring the switch to put the server on the same VLAN as the wireless network. I need to work a bit more on how to get our docker hosts to get the networking right. Since I only work part time (I'm still in college), my priority last week was just getting them functioning working for our open house event tommorrow.

My understanding of docker is that the default behavior puts all the docker hosts on an internal network, which is going to have to be bridged out to the physical network on the same VLAN as the wireless network in order for this to even function inside of docker.

It'll also be important to document some suggestions for deployment in environments where the servers don't usually live on the same VLAN as the wireless network, otherwise the docker file really won't be that helpful. I'm going to have to write a fair amount of documentation for work, so I'll be contributing back some of that work as well.

**Comment by Brekmister** [comment]
There is a trick with docker-compose where you can bridge the networking config and have everything deploy with just `docker-compose up`. If you want multiple instances, you will want to set additional static IP addresses on your server and have docker-compose listen on that IP.

**FYI:** This feature doesn't work with IPv6 for some reason.

**Comment by Brekmister** [comment]
Nevermind that last thought, I got this :)

**Comment by superhawk610** [comment]
So @ocelotsloth is this officially dead? Seems like the lack of dbus basically prevents it from working. @Brekmister's suggestion of running inside a virtual machine seems like the best solution, but that's not really anything we can build into multicast, that's up to the user.

**Comment by Brekmister** [comment]
@superhawk610 This issue is dead. Please close it.
