### ISSUE TITLE
Feature Request: Option to adjust alert font size

### ISSUE THREAD

**Issue by ocelotsloth** [superhawk610/multicast#12]
Alternatively the font size could just be increased. The TV's I'm deploying this to are mounted on the wall in hallways so the existing font size in the push notifications is pretty impossible to read from farther than a couple meters.

**Comment by Brekmister** [comment]
We can update the css from the menu like what I am trying to do with https://github.com/superhawk610/multicast/pull/15/commits/9a11db237b258931cf06af85663146d0f7e657a

Except I need to find a way to read .pug files that doesn't make my eyes cry.

**Comment by superhawk610** [comment]
I believe the alert font size has been increased to an acceptable default size. If anyone would like to implement variable font sizing, just submit a PR.
