### ISSUE TITLE
Feature Request: Slide Deck Template

### ISSUE THREAD

**Issue by ocelotsloth** [superhawk610/multicast#16]
I've got a functioning html page that does a really good job of rendering a powerpoint slide deck on the chrome casts. Using anything with any real motion or complicated transitions ends up rendering at 5 or so frames per second, which is really not very impressive.

Since it's a modified fork of another project, I'm waiting to see if the original author is willing to apply an open license to the project (https://github.com/benc-uk/simple-slides/issues/1) so that we can legally distribute modified source code. Any :+1:'s to that issue would be appreciated. I'm not sure if he noticed the email notification when I opened the issue on his repository, so additional comments from others wouldn't hurt.

If/when he licenses the project, I'll start working to incorporate my solution directly into the project. If another week or two goes by without anything happening then I'll look for other options.

Here's an example of what it looks like: http://ultron.stengle.in/slides.html

## The Real Question

I've been doing a fair bit of thinking about this and I suspect that an entirely separate application would be a better way of implementing this feature set. All it would need to do is provide channels links that can be used by multicast. An integration between the two could even be established.

Because this requires managing and uploading (possibly even generating from raw pptx files if a task runner can be set up on a Windows machine) PNG files, I suspect this would be a bit much to try and force into this application. That said, let me know what y'all think. I'm already planning on building something like this that'll have a much heavier feature set then will make sense to put into multicast, but if it would be helpful to have a simpler version that can happen.

---

All the simpler version would need for configuration is the url to the folder where the slides get put as well as a second field to set the delay between slide transitions. End users will need to figure out on their own how to setup a web server to serve the files. Adequate documentation will be necessary to explain how to use it.

If that sounds like something neat to have I'll start working on it in a few days.

**Comment by Brekmister** [comment]
Some animations work fine on my Chromecast.

While I do agree that the performance on Chromecasts are subpar in comparison to things such as Raspberry Pi's, I think we can make a completely separate project that is optimized for viewing on Chromecasts.

**Comment by ocelotsloth** [comment]
Out of curiosity which Chromecast are you running? I've only used the smaller Chromecast 1. Not sure how well the Chromecast 2 or Ultra work.

**Comment by Brekmister** [comment]
I got the new one that goes for $35 just about everywhere. I was actually
surprised when I found out it can render webpages.

The Chromecast ultra may be your best bet if you want to wild with
animations. Although as a warning, it is 70$.

On Oct 15, 2017 12:27 AM, "Mark Stenglein" <notifications@github.com> wrote:

Out of curiosity which Chromecast are you running? I've only used the
smaller Chromecast 1. Not sure how well the Chromecast 2 or Ultra work.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/superhawk610/multicast/issues/16#issuecomment-336687615>,
or mute the thread

**Comment by ocelotsloth** [comment]
Heh, yeah we've got 10 or so of the older Chromecast 1's that are the same form factor as the Roku Sticks. They're a bit underpowered.

Personally, I dislike animations in slide decks anyway, so just having a simple cut to each next slide work wonderfully for my taste.

**Comment by superhawk610** [comment]
Not to sound lazy, but I saw a few Greenscreen users saying that they just used a Google Sheets presentation as the channel URL and had it cycle for them. What advantages would this custom implementation offer over that solution?

**Comment by Brekmister** [comment]
@superhawk610 But, but, HTML5 animations! Ok, yeah whatever, I think we are in agreement that this is something you would do on the website side and not MultiCast or Chromecast side.
