### ISSUE TITLE
Feature Request: Authentication

### ISSUE THREAD

**Issue by ocelotsloth** [superhawk610/multicast#17]
I've got this deployed at a high school showing on all the hallway televisions, which lends some fairly clear reasons to want some form of authentication.

If the solution to this is just to include documentation on how to set up a reverse proxy with Nginx/Apache combined with HTTP Basic Authentication then I can write that up pretty quickly.

That said, enabling LDAP authentication would be a nice thing to have, and express has some Middleware that can be used for that.

Opinions?

**Comment by Brekmister** [comment]
+1 As it so happens, I work at a small IT shop, while everyone is very disciplined, it's a good idea to somewhat lock it down.

**Comment by superhawk610** [comment]
I agree, I'm serving this (as with most of our in-house systems) via Apache with directory-based HTTP Basic auth, and that's definitely far from efficient or secure.

I think the most straightforward solution is 2-step:

1 - Add a login splash upon first use, and redirect to this when attempting to access any page while not logged in.
2 - Generate an arbitrary 'key' (just some 24 character string) for verification of POST and DELETE requests and include it in any scripts that make them. Only allow access to the scripts when authentication has occurred.

Credentials can be saved in a Mongo collection, and authentication can be done through middleware, so this will be a fairly straightforward implementation. I'll take this one.

**Comment by superhawk610** [comment]
This issue is being incorporated into the v3.0 release milestone.
