### ISSUE TITLE
Feature Request: Error Page when Channel fails to load

### ISSUE THREAD

**Issue by ocelotsloth** [superhawk610/multicast#19]
As I mentioned in #18, if the given URL doesn't load/exist/resolve, all we get for feedback is a blank white screen. A quick JS script to detect this failure mode and change the page to show a simple error message explaining why the channel didn't load would be super helpful for diagnostics.

I'll write something next week and push it up.

**Comment by Brekmister** [comment]
I did find other things that can be diagnosed as well such as bad CSS or JS...

Ok, I totally knew I was doing...I just made some typos and used Firefox Developer tools to diagnose it. **I didn't break anything, I SWEAR**

**Comment by ocelotsloth** [comment]
What about adding a Development mode that just prints all alerts and errors to the screen as alerts on the physical chrome casts?

This would allow us to see when something isn't working in the testing phase, but also see the exact error message just in case it's different from what we get in testing browsers. Unless somebody knows how to get the developer tools working on a Chromecast.

This could be combined with a more generic page that shows when in production mode that just shows a configurable logo along with an "Oops, looks like something went wrong."

**Comment by Brekmister** [comment]
Also diagnosed in #1

**Comment by ocelotsloth** [comment]
^ Could even be combined with an api on the server that let's the chrome casts report back errors to the server to get logged in the log files.

That could be a /log/ endpoint that just takes some text and dumps it as a log message.

**Comment by Brekmister** [comment]
Actually, it's a better idea to make a log page and use a channel or template to go to it.

**Comment by Brekmister** [comment]
Communicating with the Chromecast is a piece of cake, the issue is whether
the Chromecast can report such errors.

**Comment by ocelotsloth** [comment]
Something like this should do the trick: https://stackoverflow.com/a/8000059

Just wrap the console.warn/err/etc methods so that they also do an http call to the server to report the contents of any error that is posted.

**Comment by Brekmister** [comment]
I'll experiment this a little more...I'll give you an update with results.

**Comment by superhawk610** [comment]
Chromecasts actually offer a built-in debugger via Google Chrome, accessible at `chrome://inspect`. This will list all Chromecast receivers on the LAN and allow access to their layout and console in real time.

I do think logging would be a very useful feature, for debugging in the short-term and maintenance in the long-term. I'll open a new branch for this and try to get some work done for it when I get a chance.

**Comment by Brekmister** [comment]
Just wanted to let you guys what I do right now for testing:

Just click the preview link on the device, it will render exactly the same page the chromecast is running on, including my rotation feature.
