### ISSUE TITLE
Feature Request: Add support for HTTPS

### ISSUE THREAD

**Issue by Brekmister** [superhawk610/multicast#20]
Good idea to add support and configuration for HTTPS? 

I can think of a couple things:
- publishing an app for redistribution and hosting (Digital signage to Chromecasts as a service, something my work may be very happy to do)
- Security and placing it in front of the web for whatever reason. (Also addressed in issue )

Here's how I think we can do it:
Add filepath options to the keys and certs, if not specified then just do regular http. Or we can add a page to configure all of this like WordPress.

**Comment by ocelotsloth** [comment]
Typically I accomplish this by closing the default http port (in this case 3944) and reverse proxying through Nginx/Apache. I think that's the better documented way to add your own SSL Certificates as well.

**Comment by Brekmister** [comment]
Ah, nevermind then, I forgot that my work had such reverse proxy.

**Comment by superhawk610** [comment]
You're talking about accessing Multicast's interface over HTTPS? In order for Multicast to function, the server machine must be on the same LAN network as the Chromecast devices, so I don't think this implementation could ever work as an OTA service. I think there is merit to exposing the interface to the web (namely, remote access) but I think the authentication discussed in #17 should be sufficient for this. The only real benefit offered by HTTPS is encrypted login credentials, and I think @ocelotsloth is right when he says this is easily accomplished via a reverse proxy.

I'd like to expand the README into a wiki at some point, we can add this topic there.
