### ISSUE TITLE
Feature Request: Grouping of Chromecasts

### ISSUE THREAD

**Issue by Brekmister** [superhawk610/multicast#21]
This generally can be solved by having multiple instances of MultiCast but, It would be very nice when we have large deployments to separate out different areas/departments but, notify everyone if there is a big issue.

In such case: My work wants to have digital signage for customers but, we also want to have wall mounted monitors as our war room dashboard. If there is a safety alert, we want to broadcast to all Chromecasts however, if any one of my bosses needs to hold a meeting or have an announcement, We only want to show that on our war room monitors.

**EDIT:** We already have war room monitors with Virtual Machines casting to these. But, we want something better than that such as this project

**Comment by superhawk610** [comment]
To implement this, we would need to change the way that push alerts and takeovers function, correct? Push alerts would need a new option to choose all receivers or a specific group/groups of receivers, as would takeovers. I'll need someone else to test this functionality, as my deployment only has two receivers; proper testing would require at least 3 (two to group, one to serve as a non-grouped control).

**Comment by superhawk610** [comment]
This will actually be covered over the course of splitting the service into a central controller and an arbitrary number of receiver endpoints with v3.0. I'll add it to the milestone checklist.

**Comment by Brekmister** [comment]
Actually what I was thinking now of just having tags. When you get a lot of
Chromecasts why not just filter it by location or a tag then have a bulk
select to change the channel to something? Or send a push alert to
Chromecasts with tags.

Or maybe filter by location through the IP transversal. IE. If you have a
branch or office that is in the middle of a storm the boss can make a state
of emergency and post the notification to all the screens at that location.

I would imagine this could be easily done with Mongo and I don't think we
have to change much into it.

**Comment by Brekmister** [comment]
Been a while and I would like to give a different perspective on how this would work.

If you search for something, you would get multiple results. You can then select all of them and change the channel, send an alert, takeover, etc.

It's just like doing a SQL Query and do a loop if anybody is familiar with how that works.

**Comment by superhawk610** [comment]
This issue is being incorporated into the v3.0 release milestone.
