### ISSUE TITLE
LAUNCH_ERROR

### ISSUE THREAD

**Issue by koenvb** [superhawk610/multicast#26]
Hi, 
I was trying out Multicast and got following error in my command line (mac OS X)

➜  ~ multicast start                                                                                                                     
```
MultiCast is live!
listening at port 3944...
LAUNCH_ERROR
relaunching hub...
LAUNCH_ERROR
LAUNCH_ERROR

```

The webgui works, I can register my chromecast etc but when I try to launch a channel nothing happens? Any idea what could cause this? Thanks a lot for the effort on this!

**Comment by superhawk610** [comment]
`LAUNCH_ERROR` occurs whenever the Chromecast receiver attempts to launch an application that doesn't exist or that it is not authorized to launch. Before running

```shell
multicast start
```

did you first run:

```shell
multicast config
```

Once you've done that, you'll want to confirm that the configuration values you've entered are valid. Make sure you've registered all receiver devices you're attempting to use through the [Cast SDK developer console](https://cast.google.com/u/1/publish/#/overview), and a custom Application ID that points to the local IP address of the device you're using to run Multicast.

The Receiver Application URL for your application should look something like this:

```
http://192.168.1.18:3944/landing
```

If this doesn't solve your issue, can you reply with the contents of your `.config` file?

**Comment by koenvb** [comment]
Thanks I have done the following in the dev console:

![image](https://user-images.githubusercontent.com/76891/32629240-3174fca8-c5a1-11e7-982f-9c30183416d9.png)

Then after running the multicast config I have this:

Does this look right?

```
{ mongoHost: 'localhost',
  mongoPort: 27017,
  mongoUsername: '',
  mongoPassword: '',
  mongoAuthDB: 'admin',
  appId: '103353CA' }

(y/N) y

Configuration updated! To get started, just run

```

Then when running the application I created a channel (message) look at preview all good.
Then I register my chromecast which appears correctly with a blue dot on top of it.

![image](https://user-images.githubusercontent.com/76891/32629999-b85070e8-c5a3-11e7-8579-df111e58b3b4.png)


But when saving that, nothing happens on the chromecast?
When I use the preview for the registered chromecast I see this in the dev console of the browser

```
cast_receiver.js:130 Uncaught TypeError: Cannot read property 'decrypt' of undefined
    at cast_receiver.js:130
    at cast_receiver.js:236
23:09:55.744 client.js:1 Uncaught TypeError: Cannot read property 'setLevelValue' of undefined
    at client.js:1 
```

![image](https://user-images.githubusercontent.com/76891/32629979-a8b11610-c5a3-11e7-856d-e5999425a094.png)

When I click the preview button and then go back and click on the chromecast I get this error:

```
TypeError: /usr/local/lib/node_modules/multicast/app/views/device.pug:35
    33|         option(selected, disabled, value='') Choose a Channel...
    34|         each c in channels
  > 35|           if device && device.channel && (c._id.toString() == device.channel._id.toString())
    36|             option(value=c._id, selected)= c.name
    37|           else
    38|             option(value=c._id)= c.name

Cannot read property 'toString' of undefined
    at eval (eval at wrap (/usr/local/lib/node_modules/multicast/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:399:73)
    at eval (eval at wrap (/usr/local/lib/node_modules/multicast/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:432:4)
    at template (eval at wrap (/usr/local/lib/node_modules/multicast/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:968:72)
    at Object.exports.renderFile (/usr/local/lib/node_modules/multicast/node_modules/pug/lib/index.js:428:38)
    at Object.exports.renderFile (/usr/local/lib/node_modules/multicast/node_modules/pug/lib/index.js:418:21)
    at View.exports.__express [as engine] (/usr/local/lib/node_modules/multicast/node_modules/pug/lib/index.js:465:11)
    at View.render (/usr/local/lib/node_modules/multicast/node_modules/express/lib/view.js:135:8)
    at tryRender (/usr/local/lib/node_modules/multicast/node_modules/express/lib/application.js:640:10)
    at Function.render (/usr/local/lib/node_modules/multicast/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/usr/local/lib/node_modules/multicast/node_modules/express/lib/response.js:1008:7)
    at Channel.find.sort.exec (/usr/local/lib/node_modules/multicast/app/main.js:346:13)
    at /usr/local/lib/node_modules/multicast/node_modules/mongoose/lib/query.js:3066:18
    at tryCatcher (/usr/local/lib/node_modules/multicast/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/multicast/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/multicast/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/multicast/node_modules/bluebird/js/release/promise.js:614:10)
```

**Comment by koenvb** [comment]
My main question is when does the multicast application takes over the chromecast as now multicast sees the chromecast but seems not to be able to cast to it?

**Comment by superhawk610** [comment]
Are you running Multicast via a Vagrant box/virtual server? That may be the cause of the issue. Virtual servers don't connect directly to your local network, so the IP address `10.0.0.10` won't resolve outside of your local machine. Whatever you use for the receiver URL has to be resolvable by the Chromecast's internal browser, so it either needs to be visible on your LAN (generally 192.168.1.xx) or a public URL (www.example.com).

Here's Vagrant's page on setting up a [public network](https://www.vagrantup.com/docs/networking/public_network.html) as well as a relevant [ServerFault thread](https://serverfault.com/questions/545413/expose-virtual-machine-vagrant-to-local-wifi).

**Comment by koenvb** [comment]
Not using any vagrant, our dsl router is giving us these addresses. Not sure what is happening here.

**Comment by superhawk610** [comment]
In `app/main.js`, can you make the following insertion at line 119:

```diff
+ 119      console.log('DEBUG')
+ 120      console.log(data)
```

then run Multicast and post your log output? Hopefully this will shine some light on why the hub app is having trouble launching. If you installed via NPM and are having any trouble finding the app's files, run

```shell
which multicast
```

and check there.

**Comment by GYatesIII** [comment]
I'm also experiencing the issues noted by @koenvb. The same error clicking back into the Chromecast after initially registering, and getting the LAUNCH_ERROR upon restarting multicast. If I restart multicast, the channel is displayed correctly in the Chromecasts list view and I can click into the individual Chromecast.

I added the console logs, and here's the log:
```
MultiCast is live!
listening at port 3944...
DEBUG
{ requestId: 0,
  status:
   { isActiveInput: true,
     isStandBy: false,
     volume:
      { controlType: 'master',
        level: 0.23999999463558197,
        muted: false,
        stepInterval: 0.019999999552965164 } },
  type: 'RECEIVER_STATUS' }
LAUNCH_ERROR
DEBUG
{ reason: 'CANCELLED', requestId: 1, type: 'LAUNCH_ERROR' }
DEBUG
{ requestId: 0,
  status:
   { isActiveInput: true,
     isStandBy: false,
     volume:
      { controlType: 'master',
        level: 0.23999999463558197,
        muted: false,
        stepInterval: 0.019999999552965164 } },
  type: 'RECEIVER_STATUS' }
DEBUG
{ requestId: 0,
  status:
   { isActiveInput: true,
     isStandBy: false,
     volume:
      { controlType: 'master',
        level: 0.23999999463558197,
        muted: false,
        stepInterval: 0.019999999552965164 } },
  type: 'RECEIVER_STATUS' }
DEBUG
{ requestId: 0,
  status:
   { isActiveInput: true,
     isStandBy: false,
     volume:
      { controlType: 'master',
        level: 0.23999999463558197,
        muted: false,
        stepInterval: 0.019999999552965164 } },
  type: 'RECEIVER_STATUS' }
DEBUG
{ requestId: 0,
  status:
   { applications: [ [Object] ],
     isActiveInput: true,
     isStandBy: false,
     volume:
      { controlType: 'master',
        level: 0.23999999463558197,
        muted: false,
        stepInterval: 0.019999999552965164 } },
  type: 'RECEIVER_STATUS' }
```

**Comment by superhawk610** [comment]
@koenvb @GYatesIII have you registered your Chromecast receiver as a developer device through the Cast Dev console?

**Comment by GYatesIII** [comment]
@superhawk610 Yes. It does not seem to work on other Chromecast devices I have not registered.

**Comment by superhawk610** [comment]
@GYatesIII hmm, ok. It definitely shouldn't work on non-developer devices, as they will fail when attempting to load an application ID tied to a development application, they're only authorized to open production applications.

It seems like the common thread here is a MacOS host. mDNSResponder should already be installed, you're right, and it's clearly not the problem as you're able to send/receive messages with the Chromecast device.

What generation Chromecast are you using, and is it on the latest firmware?

**Comment by GYatesIII** [comment]
@superhawk610 It's a Chromecast built into a Vizio TV, the E48-D0. It's on firmware 1.22.78594, I'm attempting to force it to update by using
```
curl -X POST -H "Content-Type: application/json" -d '{"params": "ota foreground"}' http://<chromecastIp>:8008/setup/reboot -v
```
But running into some issues.

For the computer, I'm currently upgrading from Mavericks (10.9) to High Sierra (10.13). I was using an old computer laying around that hadn't been touched in a while.

**Comment by superhawk610** [comment]
Ah, that could potentially be causing an issue. I believe the latest firmware is 1.28.x, so that's a few minor updates behind. How were you able to register the device in Google's dev console? I wouldn't imagine a built-in Chromecast would have a visible serial number...

**Comment by GYatesIII** [comment]
I'll see if I can get these built-in Chromecasts updated, I'm not optimistic though. To get the serial number, when you add a new device in the dev console, you can have it cast the serial number to the screen which is very useful.

![image](https://user-images.githubusercontent.com/3686213/32757210-5336a0d6-c8ac-11e7-9518-50394127cb32.png)

**Comment by superhawk610** [comment]
Have you made sure the following UDP ports are open on your Mac?

```shell
1900/UDP    (DIAL)
5353/UDP    (mDNS)
```

Probably can't hurt to open up 80 and 443 on TCP/UDP as well.

**Comment by GYatesIII** [comment]
After finishing the upgrade to High Sierra and updating XCode, it now casts. I'd suggest @koenvb to upgrade and see if that helps.

@superhawk610 I'm still experiencing the first issue mentioned, the `toString()` error that @koenvb  and I mentioned. It's potentially unrelated to the casting issues. The way to replicate this on my machine is to:

1. Create a new channel
1. Register a new chromecast with that new channel
1. Note that the channel in the chromecast list view on the new chromecast is blank
1. Click into the new chromecast and you see the `toString()` error message

Upon restart of multicast, the channel shows up and I can load the chromecast. I also can change the channel on a previously registered chromecast without issue.
