### ISSUE TITLE
Missing string concatenation

### ISSUE THREAD

**Issue by LucaColonnello** [superhawk610/multicast#39]
Line 67

https://github.com/superhawk610/multicast/blob/008d2ef3a84233431dc08c1852494907d713fdab/app/config.js#L66-L68

**Comment by superhawk610** [comment]
@LucaColonnello Thanks! That's what I get for doing so much of my work in the wee hours.

**Comment by superhawk610** [comment]
fixed - c79b4851e8a1c6ebb7913d78888dd6f78ccb2f6a

**Comment by LucaColonnello** [comment]
Don’t worry, it happens tomorrow everyone! :)
I spot that and I was trying to help!
By the way you might get less issue adding some linting, even a basic one! :)

Good job anyway!
