### ISSUE TITLE
Cross-origin iframe access

### ISSUE THREAD

**Issue by jonty-comp** [superhawk610/multicast#40]
Hi,

I'm just starting to deploy this in my business (it's great) but i've run into an issue that I can't find an easy solution for:

```
⏩ $('iframe')[0].contentWindow.document
⚠ SecurityError: Permission denied to access property "document" on cross-origin object
```
This is causing the "Frame loading blocked" message to display on my TV.

I'm trying to load a dashboard from another IP in the same network as the multicast server.
I've set `Access-Control-Allow-Origin: *` on my dashboard page, but it doesn't seem to make any difference.
Am I missing something obvious? 😅

**Comment by superhawk610** [comment]
One more thing to try is the `X-Frame-Options` header for your dashboard page, make sure it's set to one of the following:
```
X-Frame-Options: SAMEORIGIN
X-Frame-Options: ALLOW-FROM http://{multicast-ip:port}
```

Can you try loading the device's display on your desktop browser (click Preview on the Device entry from the Devices page) and verify that it loads correctly there? If it doesn't, what error messages do you get in the console?

Additionally, I've had some issues in the past with the `*` not being sufficient for the control origin header, so you can also try
```
Access-Control-Allow-Origin: http://{multicast-ip:port}
```
Make sure not to include a slash at the end, so it should look something like this
```
Access-Control-Allow-Origin: http://192.168.10.10:3944
```

Finally, just to make sure it's actually a CORS issue and not something else entirely, can you verify that you are able to create a channel with another URL (such as one of the two built-in channels) and display it correctly on a connected device?

**Comment by Brekmister** [comment]
You will want to add `Access-Control-Allow-Origin: multicast-url` to your
header.

You can add it simply to your html as follows:
```
<head>
  <META HTTP-EQUIV=Access-Control-Allow-Origin" CONTENT="multicast-url">
</head>
```

The way that the dashboard works is similar to how hackers try to get
malicious websites. So we have to tell the site that multicast is trusted.

**Comment by plitewaikato** [comment]
I have the same issue with my dashboards.  The channel loads correctly, but that annoying banner appears over the top.  Any way to simple disable the error reporting?

**Comment by jonty-comp** [comment]
@superhawk610 Thanks for the very quick reply!
I've tried setting the IP specifically in both `Access-Control-Allow-Origin` and `X-Frame-Options` and it doesn't seem to have made any difference, unfortunately.

Here's my local Firefox dev tools when previewing the device from Multicast:
![image](https://user-images.githubusercontent.com/1159507/34820319-073d6464-f6b8-11e7-87ce-9d2fdbbe70ea.png)

And here's Chrome's inspector connected directly to the Chromecast:
![image](https://user-images.githubusercontent.com/1159507/34820367-3cffa4cc-f6b8-11e7-9a42-fd4519032efb.png)

It's interesting that it says the X-Frame-Options header is invalid, since I cross-checked it with MDN and it looks fine!

The Nyan built-in channel displays on the TV and in my browser just fine with no error message.
In the meantime I've commented out the bit of code that displays the error, but obviously something is still fishy!

**Comment by superhawk610** [comment]
@jonty-comp looks like Chrome does not support the ALLOW-FROM syntax for X-Frame-Options, only DENY and SAMEORIGIN. Huh.

Does the page load correctly, it's just the warning message displaying incorrectly? I think my code for checking if an iframe is blocked due to CORS protection is faulty. Here's the relevant portion:

```js
function checkFrame(frame) {
  var html,
    failed = false
  try {
    var doc = frame.contentDocument || frame.contentWindow.document
    html = doc.body.innerHTML
  } catch (e) {
    failed = true
  }

  if (!html) failed = true
  if (failed)
    displayError('Frame loading blocked due to cross-origin prevention')
}
```
It attempts to fetch the document body of each iframe on the page, which, if successful, should prove that it loaded correctly. There should be a better way to do this, but as far as I can tell there is no built-in method of communicating with the browser to check if a request was blocked due to CORS or not. Any suggestions?

@plitewaikato until we can get a permanent fix, you can disable errors by making this change:
```diff
# app/lib/connection.js
addError: (device, message) => {
+  return
  // you can pass a tag directly instead of a device
```

**Comment by plitewaikato** [comment]
Thanks @superhawk610, I managed to get around this issue by making the error invisible by modifying the channel.css file.  :)

**Comment by jonty-comp** [comment]
Yes, the page itself loads fine, and i've gotten around the problem for now by commenting out the check rather than the error display, but obviously it would be nice to find a proper solution.

From a quick googling it seems like `document.onload` might work for checking if the iframe is loaded, or perhaps there's some way related to how you wanted to catch console errors from the chromecast back to the server.

**Comment by superhawk610** [comment]
The more I look around, the more it seems like there's no consistent way to accomplish this client-side. I think the correct solution is to have the server perform an OPTIONS request when saving the channel and throwing up a warning if it finds any problematic headers, such as X-Frame-Options or the like.

**Comment by plitewaikato** [comment]
I'm seeing this error with Dashboards that I previously used with Dashkiosk
and Chromecasts without X-Frame issues, so it must be possible.  But I'm
not too bothered as the workaround(s) seem fine.

**Comment by bugtoo** [comment]
We are seeing the same issues and most dashboard are not loading correctly. If we use the multicast version of october 7th the issue is not present. Any ideas?

**Comment by superhawk610** [comment]
@bugtoo can you reply/PM me with more specifics about how they're not loading correctly? Quite a bit has changed since the 1.0 release last October. If you're just having an issue with the "Frame loading blocked" error message, you can disable error reporting until a permanent fix is released using [this method](https://github.com/superhawk610/multicast/issues/40#issuecomment-356964661).

**Comment by superhawk610** [comment]
> I think the correct solution is to have the server perform an OPTIONS request when saving the channel and throwing up a warning if it finds any problematic headers, such as X-Frame-Options or the like.

I'll implement this in the next major release.

**Comment by superhawk610** [comment]
This issue is being incorporated into the v3.0 release milestone.
