### ISSUE TITLE
Chromecasts started showing 'Brain Freeze' when trying to run Multicast

### ISSUE THREAD

**Issue by technical1000heads** [superhawk610/multicast#43]
Just recently after some WiFi issues in the office all our Chromecast connections started showing 'Brain freeze' when trying to run Multicast.

It is running off a Raspberry Pi, and no matter what variation of running Multicast I use (global npm, or direct) the problem is still present. If anyone else has had this issue, or has any thoughts that would be a great help.

Multicast version: 2.0.2
All Chromecasts updated to latest firmware
WiFi/network not running IPv6 as far as I know
No errors shown in console

Any more information that may help please let me know.

**Comment by superhawk610** [comment]
From an initial glance around a few forums, it seems your WiFi band may potentially cause this issue... are you using a 2.4GHz, 5GHz, or hybrid network?

What complexity of local network are the Chromecasts/RPi running on? On a scale from 1 to 10, where 1 is your grandparents' home network and 10 is the LAN at a cybersecurity firm.

Are the Chromecasts Gen 1 or Gen 2 or are they integrated with TVs?

> after some WiFi issues in the office

Could you go into any more detail on those issues?

**Comment by technical1000heads** [comment]
I did find the same thing after some searching. I will have to get in touch with our wonderfully outsourced IT people to see if they have been messing about with the WiFi.

I'd say it is somewhere in the middle, it is certainly no high-end networking. Chromecast wise it is a mix of Gen 1 and Gen 2. 

All were working just fine before the issues, which were around dropouts and really slow network speeds.

I will come back once I see what I can find out.

**Comment by superhawk610** [comment]
Any update on this?

**Comment by superhawk610** [comment]
@technical1000heads @Buravchik does the Chromecast go immediately to the Brain Freeze error, or does it successfully display any Multicast content for any period of time?

**Comment by plitewaikato** [comment]
Just started getting this too.  Brain Freeze, then restart.

**Comment by plitewaikato** [comment]
No Multicast content gets displayed

**Comment by superhawk610** [comment]
Alright, it's clear that this is no longer an isolated incident, but as of yet I am still unable to replicate it.

When this happens, does Multicast display anything in the logs?

**Comment by plitewaikato** [comment]
Bit of progress, I noticed that I've been unable to register now Chromecasts in the Google Developer page the last few days.  I went in there and created a new Application ID and re-ran the multicast config setup process, updating the AppID.  After about fifteen minutes the Chromecasts started functioning again.

**Comment by superhawk610** [comment]
Interesting. Was there any sort of error message displayed for the previous application ID?

**Comment by plitewaikato** [comment]
Nope, but just prior to this happening I noticed the ability to register new Chromecasts had been restored.  And I think there was a firmware upgrade pushed last night?

**Comment by plitewaikato** [comment]
Oh and thanks, this is a splendid tool.  :)

**Comment by plitewaikato** [comment]
Final thing, I had to manually powercycle the Chromecasts.  Usually I do a restart with a script using `http://xxx.xxx.xxx.$i:8008/setup/reboot -d '{"params":"now"}' -X POST --connect-timeout 1 `but that wasn't enough this time

**Comment by superhawk610** [comment]
Lots of good information here to try @technical1000heads @Buravchik.

**Comment by Buravchik** [comment]
I was able to fix my Brain Freeze problem. It was my bad: i was experimenting with deploying Multicast server on different platforms and forgot to change ip of App backend: https://cast.google.com/u/0/publish/#/applications/edit/YOURAPPID
After correcting Receiver Application URL and rebooting chromecast BrainFreeze problem disappeared.

**Comment by technical1000heads** [comment]
Excellent. I will have a go at these things and see what happens.

**Comment by superhawk610** [comment]
Looks like this has been figured out. Feel free to reopen if the solutions posted here do not work for you.
