### ISSUE TITLE
Usage question on OSX

### ISSUE THREAD

**Issue by rajasaur** [superhawk610/multicast#45]
Sorry, Im not sure what Im missing to get this setup.
I have the node module installed and configured. I can check in mongo that the chromecast and channels are setup. However, on my TV the URLs configured on the channel are not showing up.

If I cast my Tab directly then I can see whats on the screen (which is what it should do), but Im not sure what I need to do to get the URLs to appear when the channel is configured.

OSX probably has mDNSResponder built in , so I had no issues installing node_mdns also. 

Steps:
1. Installed multicast and ran configure. Started multicast
2. Registered the application using the local url and set it to http://ip:3944/landing
3. Visited the page on browser at http://ip:3944
4. Setup a channel to display the Nyan
5. Since the chromecast was in the same network, it automatically appeared on my "devices" link. I edited to add the channel that was setup above.

Im assuming at this point, the chromecast should switch to show the URL, but its not. There is no firewall setup on my machine either. 

I will try with Linux tomorrow, but just wanted to see if Im missing something basic.

Thanks
raja

**Comment by superhawk610** [comment]
Sorry you're having trouble getting started, it sounds like you followed the setup instructions correctly.

Do you see this screen on your Chromecast once you launch Multicast?

![screenshot_2018-06-05 multicast setup](https://user-images.githubusercontent.com/18172185/40997326-3bdf3f12-68d2-11e8-8f99-dcc142dc03d0.png)

**Comment by rajasaur** [comment]
Thanks for the quick response @superhawk610 . Once I restart the device , I get the above display. So, it looks like chromecast talked back to the /landing to get this page.   

(Not really connected, but The multicast server crashed during the restart with the following stack:
`
/Users/raja/projects/javascript/multicast/node_modules/castv2/lib/client.js:128
  this.ps.send(buf);
          ^

TypeError: Cannot read property 'send' of null
    at Client.send (/Users/raja/projects/javascript/multicast/node_modules/castv2/lib/client.js:128:11)
    at Channel.send (/Users/raja/projects/javascript/multicast/node_modules/castv2/lib/channel.js:34:12)
    at Timeout.d.pulse.setInterval [as _onTimeout] (/Users/raja/projects/javascript/multicast/app/lib/connection.js:51:32)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)`

**Comment by rajasaur** [comment]
Actually, it does work now. It looks like I had to restart the chromecast. Now that I restarted, both the URLs configured on my channel started playing on the Chromecast.

Thanks a lot for this.

**Comment by superhawk610** [comment]
@rajasaur Thanks for that stack trace, we've seen the `this.ps.send(buf)` crop up a few times already, I'm hoping to stomp it out by the next major release. Enjoy!
