### ISSUE TITLE
Allow variable page zoom

### ISSUE THREAD

**Issue by superhawk610** [superhawk610/multicast#47]
Chrome tries its best to determine the correct level of page zoom and generally gets it right, but on more than one occasion, a page that renders correctly on desktop will be too large or too small on the Chromecast's display.

Each channel should have a zoom control (that defaults to 100%) to allow for fine tweaking of this fit to display.

**Comment by JackToveyMP** [comment]
How would one modify this in the current version, currently my screens are displaying at 100%, need them closer to 75%

**Comment by superhawk610** [comment]
Currently there's no official support for this, but you should be able to hack it by applying a CSS zoom to the `<body>` element on the page you're casting, something like

```css
body {
  zoom: 75%;
}
```

**Comment by JackToveyMP** [comment]
I take it that is in the actual page I am casting, rather than the CSS in your project

**Comment by superhawk610** [comment]
Either one would work! If you're going to be using the page you're casting outside of this project, you probably don't want to modify the zoom, so you could just apply it to the template you're using to cast, so for `app/views/layouts/fullscreen.pug`, you could add it like so

```pug
doctype html
html(lang='en')
  head
    title Multicast | #{channel.name}
    include ../include/head.pug
    link(rel='stylesheet', href='/css/channel.css')

  body.fullscreen(class=rotation, style='zoom: 75%')
    include ../include/error.pug
    include ../include/toast.pug
    if channel.URLs != null && channel.URLs.length
      iframe(src=channel.URLs[0][0], frameborder=0, framespacing=0)
    
    include ../include/rotation.pug
    script(type='text/javascript', src='/js/jquery.min.js')
    script(type='text/javascript', src='/socket.io/socket.io.js')
    if casting
      script(type='text/javascript', src='//www.gstatic.com/cast/sdk/libs/receiver/2.0.0/cast_receiver.js')
    script(type='text/javascript', src='/js/app.js')
    script(type='text/javascript', src='/js/client.js')
```

**Comment by JackToveyMP** [comment]
No Dice, need a way to zoom the iframe in and out on the fullscreen, that method just made it larger or smaller. Also tried editing the css files, not sure if I am missing a step though

**Comment by JackToveyMP** [comment]
no dice there I am afraid, need to adjust the zoom of the contents of the iframe, without making the iframe itself smaller, any ideas?

**Comment by JackToveyMP** [comment]
Actually solved this, made the following change in `/build/css/channel.css`

```
body.fullscreen iframe {
  width: 200vw;
  height: 200vh;
  transform: scale(0.5) translate(-50%,-50%);
}
```

This might help with adding this to your project

**Comment by superhawk610** [comment]
This issue is being incorporated into the v3.0 release milestone.
