### ISSUE TITLE
How can I actually cast my web page?

### ISSUE THREAD

**Issue by misosec** [superhawk610/multicast#49]
Hello,
so I registered my TV Cheromecvast and added local webpage as a chanell. How can I cast it to my TV? When I click preview in Devices or Channels, I can only see my wewbpage in the browser only.

Thank you.

**Comment by superhawk610** [comment]
From the Devices page (top right), make sure your Chromecast device is visible. Click **Register Chromecast**, and fill in the form, making sure to select the channel you created as its **Channel**. Once you save, it should appear on your Chromecast!

If you have any trouble, try restarting Multicast.

**Comment by superhawk610** [comment]
What do you see on your TV? Did you follow all the Chromecast Developer Console setup (listed in the readme) to activate your Chromecast as a developer device?

**Comment by misosec** [comment]
Hello,
I can see only my TVs home screen (app launcher).

**Comment by superhawk610** [comment]
Hmm, ok. Let's do some further debugging and see if we can figure out why they're not talking to each other.

Did you open these ports on your host machine?

```
1900/UDP (DIAL)
5353/UDP (mDNS)
80/TCP/UDP (HTTP)
443/TCP/UDP (HTTPS)
```

You can add the following lines in `app/lib/connection.js` to add some basic communication debug logging:

```diff
  // line 64
  // monitor receiver status updates to insure hub is open
  d.receiver.on('message', (data, broadcast) => {
+   console.log(Date.now(), data.type, data)
    if (data.type != 'RECEIVER_STATUS')
```

If you've installed globally, you can run

```
which multicast
```

to find your installation directory.

Relaunch Multicast and post your log output after the first 2 minutes or so.

**Comment by misosec** [comment]
Hello,
I am on Ubuntu (VMWare with bridged connection) and I used `sudo ufw allow` to open those ports so I guess it should be ok. 
Here is a log:

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
MultiCast is live!
Listening at port 3944...
1543254881020 'LAUNCH_ERROR' { reason: 'NOT_FOUND', requestId: 1, type: 'LAUNCH_ERROR' }
connected client with host: 192.168.100.210
disconnected client with host: 192.168.100.210
(node:2434) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.

```

Thank you.

**Comment by superhawk610** [comment]
Are the host and Chromecast on the same network? How is your subnet configured? I notice you're using a non-standard 192.168.100.xxx scheme, it may be that the Chromecast can't resolve that URL.

Open up Chrome from a computer on your network (your host machine, for example) and head to

```
chrome://inspect
```

Your developer enabled devices should appear here. Inspect one of them, and then in the console in the window that pops up, attempt to make a `fetch` request to your host machine (eg - `fetch(192.168.100.212:3944/landing).then(res => res.json()).then(json => console.log(json))`). Is that request successful? If not, what sort of error does it throw? You can also check in the Network tab of the inspector to see more details on the request and why it fails.

**Comment by misosec** [comment]
Just to be sure, in Google Cast SDK App should be IP of my TV and not IP of my Ubuntu machine with MultiCast, correct?

**Comment by superhawk610** [comment]
Ah! No, it should be the IP of your Ubuntu machine.

**Comment by superhawk610** [comment]
If you get the same error log at first (`LAUNCH_ERROR`) then you may have to reboot your Chromecast before trying again (so it fetches the updated launch URL from the server).

**Comment by superhawk610** [comment]
Sorry, the URL has to include the protocol (`http://`), try this

```
fetch('http://192.168.100.212:3944/landing')
  .then(res => res.json())
  .then(json => console.log(json))
```

**Comment by superhawk610** [comment]
Does your BRAVIA show anything besides the IP address? See the below screenshot:

![inspect](https://user-images.githubusercontent.com/18172185/49041241-ae80dc80-f192-11e8-99c8-ab80d97510f4.png)

You should run the `fetch` code from that **inspect** link.

**Comment by misosec** [comment]
No, there is just IP of my TV.
Here is `fetch` response

![image-001- 21-46-55](https://user-images.githubusercontent.com/29805226/49041346-4ac3d700-f1c5-11e8-804f-8df9b6a5f746.png)

And here is `Network Preview`
![image-001- 21-48-44](https://user-images.githubusercontent.com/29805226/49041407-6d55f000-f1c5-11e8-8e4e-065a28b444b1.png)

I don't understand. I did register my Chromcast device:
![image-001- 21-52-43](https://user-images.githubusercontent.com/29805226/49041486-a2624280-f1c5-11e8-933d-b54cf275ee5e.png)

**Comment by superhawk610** [comment]
Can you paste the contents of your `.config` file?

**Comment by misosec** [comment]
```
{
  "mongoHost": "localhost",
  "mongoPort": 27017,
  "mongoUsername": "mike",
  "mongoPassword": "password",
  "mongoAuthDB": "admin",
  "appId": "xxxxxx"
}
```

**Comment by superhawk610** [comment]
Can you double check and make sure the `appId` matches the one shown in your Cast Developer Console? In the past, `LAUNCH_ERROR` has been a result of an `appId` mismatch.

**Comment by superhawk610** [comment]
When you launch Multicast, does your Chromecast TV seem to do anything at all? Does it flicker to a blank white/black screen or show the Multicast green landing page, or no?

**Comment by superhawk610** [comment]
@nebev in #34 was also using Sony Bravia TVs with built-in Chromecast and they worked alright, so I don't think that's the problem. I've pushed a handful of minor bugfixes recently without very extensive testing, so it's possible something weird slipped in without my notice. If this is the case, you can try checking out an earlier version and running from there.

```
git clone https://github.com/superhawk610/multicast.git
cd multicast
# checkout the most recent stable commit
git checkout a2d4b737cc79eeb97e2c85b620b3632f3ff8e400
```

That's just about all I know to do to debug the current version, but I'm not very happy with it so I am currently working on a complete rewrite using a more modern TypeScript/GraphQL stack. You can track progress on the `next` branch, but I expect it to be 2 weeks or so before it's usable. Sorry for putting you through so much trouble, we'll definitely find a way to get you up and running! I'll update you on v3.0 progress as it comes.

**Comment by misosec** [comment]
You don't have to appologize... I am realy thankfull for your help because I learned thing or two. I will try clean installation on some other device (Pi 3B+ probably) and I will be tracking next branch for sure as well.

Thank you again.

**Comment by superhawk610** [comment]
I'm closing all `v2.x` issues that are no longer relevant to the upcoming v3.0 release. The underlying framework is changing so drastically that it's unlikely this bug will be reproducible. Feel free to comment further if this issue persists in v3.0.
