### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by Brekmister** [superhawk610/multicast#5]
Before any more Pull Requests are merged, I very strongly suggest that @superhawk610 makes an actual GitHub release marking what he has done.

While these pull requests may contain very good points, they may not necessarily be perfect. It already works, so let's mark it as the starting point before it stops working.

@superhawk610 If you need help understanding or implementing this, PM me.

**Comment by superhawk610** [comment]
Great point, I'm marking my work (plus your brief edit of the readme) as v0.1, and we'll go from here!
