### ISSUE TITLE
Could not connect to Mongo.

### ISSUE THREAD

**Issue by somiom** [superhawk610/multicast#54]
Hello,
I followed the installation instructions, but I'm stuck, I need help. what am I doing wrong?
![2019-03-06 23_37_09-pi raspberrypi_](https://user-images.githubusercontent.com/48300177/53920360-2ea9be80-406d-11e9-80a6-5eaec1280a86.png)

**Comment by superhawk610** [comment]
Can you post your `.config` file? Are you able to connect to your mongo instance from the CLI (eg - `mongo`)?

**Comment by somiom** [comment]
Thanks for the reply. 
If you were thinking of the config file of MangoDB, it is below. 
[mongodb.pdf](https://github.com/superhawk610/multicast/files/2941371/mongodb.pdf)


And I can connect to mongo shell.

![mongodb shell](https://user-images.githubusercontent.com/48300177/53958937-90584000-40e2-11e9-9229-877a8a752bbc.png)

**Comment by superhawk610** [comment]
Before you run MultiCast for the first time, be sure to configure it

```
multicast config
```

and fill out the requested values.

**Comment by somiom** [comment]
> and fill out the requested values.

I've tried a lot of times, but I could not find out which data should be entered. I did not find anything in the instructions.

![multicastconfig](https://user-images.githubusercontent.com/48300177/53972525-3dd94c80-40ff-11e9-90ba-01779c2cf35e.png)

**Comment by superhawk610** [comment]
Yeah, that looks correct. If you haven't set a username/password for Mongo or changed the authDb, you can use the default values. For Application ID, yes, use your GoogleCast SDK AppID. The final output should look like:

```
  mongoHost: 'localhost',
  mongoPort: 27017,
  mongoUsername: '',
  mongoPassword: '',
  mongoAuthDB: 'admin',
  appId: 'YOUR_GOOGLECAST_SDK_APP_ID'
```

Run `multicast config` with those options and then try `multicast start` again and let me know if it works.

**Comment by superhawk610** [comment]
If that doesn't work and you feel comfortable editing JS, you can find your install directory

```
which multicast
```

and edit the `dbConnect.js` lib to output the stacktrace for what's causing the connection error:

```diff
// app/lib/dbConnect.js
// line 16
-    .catch(() => console.log('Could not connect to Mongo.'))
+    .catch(e => {
+      console.log('Could not connect to Mongo.'))
+      console.error(e)
+    })
```

**Comment by somiom** [comment]
Same error: "Could not connect to Mongo.".
I changed dbConnect.js as you described, and now I have this:

![multicastdbconnecterrlog](https://user-images.githubusercontent.com/48300177/53993837-c2908e80-4130-11e9-9b6f-0ed2eee31c2f.png)

**Comment by superhawk610** [comment]
Ahh, looks like your Mongo installation is out of date. You'll have upgrade to at least v2.6, though you may as well go ahead and update to the latest version (v4.0 as of time of writing). You can find installation instructions for the latest version [here](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/).
