### ISSUE TITLE
old cache appears

### ISSUE THREAD

**Issue by Buravchik** [superhawk610/multicast#57]
I have a channel with two URLs in one section.
* First one is just page from internal server which shows some generated picture (building plan with statuses of equipment). (lets name it A)
* Second one is just a [published](https://support.google.com/docs/answer/183965?co=GENIE.Platform%3DDesktop&hl=en) Google Spreadsheet. (lets name it B) Published spreadsheet update period is less then 5 minutes. I have added few formulas to spreadsheet to see current time of spreadsheet when it was republished.

What i see on my channel for example when data is recently updated and url to published spreadsheet already have new data:
1. A
2. updated B
3. A
4. old B
5. A
6. updated B
7. A
8. old B
9. and so on.

So, it looks like Multicast have issues with caching page content. How to force expire cache?

**Comment by superhawk610** [comment]
Added to v3.0 release milestone.
