### ISSUE TITLE
how to edit app/lib/connections.js

### ISSUE THREAD

**Issue by thomasvjohansen** [superhawk610/multicast#65]
Hi
think this is a great project and testing for my work.
but I have the CORS issue, because my webpage uses <script>

I want to make this change to avoid the visual error:

```
# app/lib/connection.js
addError: (device, message) => {
+  return
  // you can pass a tag directly instead of a device
```

but where can I find this (ubuntu server)
normally it would be in the var/web but cant find the file anywere.

Is it all stored in the mongodb? and then how do I edit the connection.js file?

Is there another way to avoid 
"Error! Frame loading blocked due to cross-origin prevention"

when using <script>?

Im not getting content from other urls.

**Comment by thomasvjohansen** [comment]
I figured out how to workaround "Error! Frame loading blocked due to cross-origin prevention"
as sugested from another user, edit the channel.css and alter the visuals of the error message.

Edit: 
/usr/local/lib/node_modules/multicast/public/css/channel.css

change top:0; to a place outside of view, in my setup 5000px will do the trick:
`#error
{
position:absolute;
top:5000px;
left:0;
width:100vw;
background:#000;
color:#fff;
padding:20px
}
`

**Comment by metalcoat** [comment]
Thanks for this!
