### ISSUE TITLE
Timing of content

### ISSUE THREAD

**Issue by metalcoat** [superhawk610/multicast#67]
I'm currently using multicast (THANK YOU!) to display a 4 TV menu.  I would like to add a feature request for 3.x that would allow different timing for different slides, or maybe this is something I can edit in the current version?  For example I want to show the Menu 90% of the time and then for the 10% create burn-in prevention content that also would advertise products.

**Comment by thomasvjohansen** [comment]
As a workaround, couldn't you just have the frames in your own websource, instead of using the channels frame setup? Still a workaround....

**Comment by metalcoat** [comment]
Yes I can, and probably will set this up. But right now for ease I'm displaying Google Slides to allow employees and other non-technical users to edit pricing, etc.

**Comment by superhawk610** [comment]
Thanks for the suggestion @metalcoat!

I believe this is a useful feature to have. I've added it to the 3.1 milestone.
