### ISSUE TITLE
Refeshing cached of images on chromecast or multicast

### ISSUE THREAD

**Issue by thomasvjohansen** [superhawk610/multicast#76]
This is not a "real" issue of multicast.

But more of finding a good solution for updating content in a current channel.

I have a webpage, where I only want to replace the pictures with new content.
Even though I upload new pictures with same name, and reloads the channel on the chromecast, it still shows the old pictures.

Have even tried to change picture names and altered the webpage for those new files names. but its as if it still loads a cached version of the page on the chromecast.

have one of you found an easier way, without rebooting the chromecast or server?
Or should I make a renamed copy of the webpage url to force it to reload everything?

**Comment by LBegnaud** [comment]
I would think this could be a function of your webserver, but one trick to invalidating caches is to add a useless parameter. so if your site is `https://webserver/page` change the channel to `https://webserver/page?dummy=1`

This would cause the page reload when you save the channel, and it will likely make the chromecast not cache. if it works, might be a functional workaround if you aren't changing images much

**Comment by thomasvjohansen** [comment]
Closing it.
