### ISSUE TITLE
Feature Request: Screen rotation

### ISSUE THREAD

**Issue by Brekmister** [superhawk610/multicast#8]
Add options to rotate the screen. I will get cranking on it and make a Pull Request

**Comment by superhawk610** [comment]
@Brekmister do you plan on using a `transform: rotate()` via CSS?

**Comment by Brekmister** [comment]
I do somewhere but, also setting max width and height of the div so the webpage can still be responsive. there may be some JavaScript tricks with the Iframe too.

**Comment by superhawk610** [comment]
Sounds good, look forward to seeing what you come up with.

**Comment by Brekmister** [comment]
I added support in PR https://github.com/superhawk610/multicast/pull/15

Someone else should be able to go through these .pug files and back-end javascript to emit the 'rotate' event on socket.io

**Comment by Brekmister** [comment]
Update: PR #15 works really amazing now.

**Comment by superhawk610** [comment]
Awesome. Check out my review and I'll commit it.
