### ISSUE TITLE
Feature Request: Make project a global NPM package with cli

### ISSUE THREAD

**Issue by Brekmister** [superhawk610/multicast#9]
There are several advantages of this:
1. Configuration - set the App ID, mongo DB credentials and host (and verify these are valid)
2. Start detached or daemonize it 
3. Unified cli command: 'multicast ...'
4. 'npm install -g multicast' boom done

Point being, This is where I think multicast should go. I can probably get started on a thing this weekend to merge in. No guarantees though.

**Comment by superhawk610** [comment]
Good idea. I'll work on this since I'll have to register the package through NPM.

**Comment by superhawk610** [comment]
Currently waiting to hear back from the owners of [multicast](https://www.npmjs.com/package/multicast) on NPM.

**Comment by superhawk610** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [NPM Package for distribution](https://trello.com/c/1pDgP4fi/1-npm-package-for-distribution)

**Comment by superhawk610** [comment]
Package is now available for install [here](https://www.npmjs.com/package/multicast) via NPM. Let me know how it works for everyone.
Daemonized/detached function is the last piece to implement before closing this issue.

**Comment by Brekmister** [comment]
Welp, I found an issue with installing via NPM.

```
> multicast@1.0.0 postinstall /usr/lib/node_modules/multicast
> gulp

module.js:471
    throw err;
    ^

Error: Cannot find module 'gulp-uglify-es'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/multicast/gulpfile.js:2:46)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by superhawk610** [comment]
You could be right about avoiding Gulp, but I don't think that's the cause of the error. I added a potential fix for this in the README:

**Can't launch after installing via NPM?**

Make sure your `NODE_PATH` environment variable correctly includes the global store for node dependencies. On Linux:

```shell

export NODE_PATH=/opt/lib/node_modules

```

**Comment by Brekmister** [comment]
Sweet Deal. There are some other features I would like to add to the CLI but, for right now, this issue is fixed.
